Areas/Admin/Controllers/AdminImagesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using VendaLanches.Models;

namespace VendaLanches.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class AdminImagesController : Controller
    {
        private readonly ConfigurationImages _myConfig;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public AdminImagesController(IWebHostEnvironment webHostEnvironment, IOptions<ConfigurationImages> myConfiguration)
        {
            _webHostEnvironment = webHostEnvironment;
            _myConfig = myConfiguration.Value;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> UploadFiles(List<IFormFile> files)
        {
            int maxFilesByUpload = 10;
            if (files == null || files.Count == 0)
            {
                ViewData["Erro"] = "Error: Arquivo(s) não selecionado(s)";
                return View();
            }            
            if (files.Count > maxFilesByUpload)
            {
                ViewData["Erro"] = $"Error: Quantidade de arquivos excedeu o limite máximo - {maxFilesByUpload};";
            }

            long totalFileSize = files.Sum(f => f.Length);

            List<string> filesPathsNames = new List<string>();
            var filePath = Path.Combine(_webHostEnvironment.WebRootPath, _myConfig.NomePastaImagensProdutos);

            foreach (var formFile in files)
            {
                if (formFile.FileName.Contains(".jpg") || formFile.FileName.Contains(".gif") || formFile.FileName.Contains(".png"))
                {
                    string fileNameWithPath = string.Concat(filePath, "\\", formFile.FileName);
                    filesPathsNames.Add(fileNameWithPath);
                    using (FileStream stream = new FileStream(fileNameWithPath, FileMode.Create))
                    {
                        await formFile.CopyToAsync(stream);
                    }
                }
            }

            ViewData["Resultado"] = $"{files.Count} arquivos foram enviados ao servidor, " +
                $"com tamanho total de: {totalFileSize} bytes";
            ViewBag.Arquivos = filesPathsNames;
            return View(ViewData);
        }

        public IActionResult GetImages()
        {
            FileManagerModel model = new FileManagerModel();
            var userImagesPath = Path.Combine(_webHostEnvironment.WebRootPath, _myConfig.NomePastaImagensProdutos);

            DirectoryInfo dir = new DirectoryInfo(userImagesPath);
            FileInfo[] files = dir.GetFiles();
            model.PathImagesProduto = _myConfig.NomePastaImagensProdutos;
            if (files.Length == 0)
            {
                ViewData["Erro"] = $"Nenhum arquivo encontrado na pasta {userImagesPath}";
            }
            model.Files = files;
            return View(model);
        }

        public IActionResult DeleteFile(string fname)
        {
            string _imagemParaDeletar = Path.Combine(_webHostEnvironment.WebRootPath, _myConfig.NomePastaImagensProdutos + "//", fname);
            if (System.IO.File.Exists(_imagemParaDeletar))
            {
                System.IO.File.Delete(_imagemParaDeletar);
                ViewData["Deletado"] = $"Arquivo(s) {_imagemParaDeletar} apagado com sucesso.";
            }
            return View("index");
        }
    }
}

Areas/Admin/Views/AdminImages/GetImages.cshtml
@model FileManagerModel
@{
    ViewBag.Title = "Arquivos";
}

@if (Model.Files != null)
{
    <h3>Imagens:</h3>
    <hr />
    var caminho = Model.PathImagesProduto;
    <div class="row">
        @foreach (FileInfo file in Model.Files)
        {
            <div class="column">
                <img src="~/@caminho/@file.Name" width="100" height="100">
                <div style="padding:10px;text-align:left">
                    <a href="@Url.Action("DeleteFile","AdminImages", new {fname = file.Name})">Apagar</a>
                </div>
            </div>
        }
    </div>
}

Areas/Admin/Views/AdminImages/Index.cshtml
<table border="0" width="100%">
    <tr>
        <td>
            <form method="post" enctype="multipart/form-data" asp-controller="AdminImages" asp-action="UploadFiles">
                <img src="~/Images/Upload.png" width="50" height="50" />
                <div class="form-group">
                    <div class="col-md-10">
                        <p><b>Selecione um ou mais arquivos para enviar: </b></p>
                        <p>(Arquivos com o mesmo nome serão sobrescritos)</p>
                        <input type="file" name="files" multiple class="button btn-outline-primary" />
                    </div>
                </div>
                <hr />
                <div class="form-group">
                    <div class="col-md-10">
                        <input type="submit" value="Enviar arquivos(s)" class="button btn-outline-primary" />
                    </div>
                </div>
            </form>
        </td>
        <td>
            <form method="post" enctype="multipart/form-data" asp-controller="AdminImages" asp-action="GetImages">
                <img src="~/Images/VisualizarImagem.jpg" width="50" height="50" />
                <div class="form-group">
                    <div class="col-md-10">
                        <p><strong>Selecione uma imagem para visualizar: </strong></p>                        
                    </div>
                </div>
                <hr />
                <div class="form-group">
                    <div class="col-md-10">
                        <input type="submit" value="Visualizar arquivos de imagens" class="button btn-outline-warning"/>
                    </div>
                </div>
            </form>
        </td>
    </tr>
</table>
<div class="container">
    @if (ViewData["Deletado"] != null)
    {
        <li>@ViewData["Deletado"]</li>
    }
</div>

Areas/Admin/Views/AdminImages/UploadFiles.cshtml
@{
    ViewData["Title"] = "UploadFiles";
}

<img src="~/Images/Upload.png" width="50" height="50"/>
<hr/>
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        @if (ViewData["Erro"] != null)
        {
            <img src="~/Images/error.png" width="50" height="50"/>
            <h4>@ViewData["Erro"]</h4>
        }
    </div>
    <div class="container">
        @if (ViewData["Resultado"] != null)
        {
            <h4>@ViewData["Resultado"]</h4>
            <hr/>
            @if (ViewBag.Arquivos != null)
            {
                @foreach (string arquivo in ViewBag.Arquivos)
                {
                    <li>
                        @arquivo
                    </li>
                }
            }
        }
    </div>
</div>