Areas/Admin/Controllers/AdminGraficoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using VendaLanches.Areas.Admin.builder.Services;

namespace VendaLanches.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class AdminGraficoController : Controller
    {
        private readonly GraficoVendasService _graficoVendas;

        public AdminGraficoController(GraficoVendasService graficoVendas)
        {
            _graficoVendas = graficoVendas ?? throw
                new ArgumentNullException(nameof(graficoVendas));
        }

        public JsonResult VendasLanches(int dias)
        {
            var lanchesVendasTotais = _graficoVendas.GetVendasLanches(dias);
            return Json(lanchesVendasTotais);
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult VendasMensal()
        {
            return View();
        }

        [HttpGet]
        public IActionResult VendasSemanal()
        {
            return View();
        }

    }
}

Areas/Admin/Views/AdminGrafico/Index.cshtml
<title>
    @ViewData["Title"] - Gráfico de Vendas
</title>


<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<div id="chart_div" style="width: 900px; height: 500px;"></div>
<script type="text/javascript">
    google.charts.load('current', { 'packages': ['corechart'] });
    google.charts.setOnLoadCallback(carregarDados);

    function carregarDados() {
        $.ajax({
            url: '@Url.Action("VendasLanches", "AdminGrafico")',
            data: { dias: 365 },
            dataType: 'json',
            type: 'GET',
            success: function (xhr, status, error) {
                var err = eval("(" + xhr.responseText + ")");
                toastr.error(err.Message);
            },
            success: function (data) {
                GraficoVendasLanches(data);
                return false;
            }
        });
    }

    function GraficoVendasLanches(data) {
        var dataArray = [['Lanche', 'Quantidade', 'Valores(R$)']];
        
        $.each(data, function (i, item) {
            dataArray.push([item.lancheNome, item.lanchesQuantidade, item.lanchesValorTotal]);
        });
        
        var data = google.visualization.arrayToDataTable(dataArray);
        var options = {
            title: 'Lanches - Vendas no último ano',
            chartArea: { width: '70%' },
            colors: ['#b0120a', '#ffab91'],
            hAxis: {
                title: 'Valor Total (R$)',                
                minValue: 0
            },
            vAxis: {
                title: 'Lanches'
            }
        };
        var chart = new google.visualization.BarChart(document.getElementById('chart_div'));
        chart.draw(data, options);
        return false;
    }
</script>

Areas/Admin/Views/AdminGrafico/VendasMensal.cshtml
<title>
    @ViewData["Title"] - Gráfico de Vendas
</title>


<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<div id="chart_div" style="width: 900px; height: 500px;"></div>
<script type="text/javascript">
    google.charts.load('current', { 'packages': ['corechart'] });
    google.charts.setOnLoadCallback(carregarDados);

    function carregarDados() {
        $.ajax({
            url: '@Url.Action("VendasLanches", "AdminGrafico")',
            data: { dias: 30 },
            dataType: 'json',
            type: 'GET',
            success: function (xhr, status, error) {
                var err = eval("(" + xhr.responseText + ")");
                toastr.error(err.Message);
            },
            success: function (data) {
                GraficoVendasLanches(data);
                return false;
            }
        });
    }

    function GraficoVendasLanches(data) {
        var dataArray = [['Lanche', 'Quantidade', 'Valores(R$)']];

        $.each(data, function (i, item) {
            dataArray.push([item.lancheNome, item.lanchesQuantidade, item.lanchesValorTotal]);
        });

        var data = google.visualization.arrayToDataTable(dataArray);
        var options = {
            title: 'Lanches - Vendas nos últimos 30 dias',
            chartArea: { width: '70%' },
            colors: ['#b0120a', '#ffab91'],
            hAxis: {
                title: 'Lanches',
                minValue: 0
            },
            vAxis: {
                title: 'Valor total (R$)'
            }
        };
        var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
        chart.draw(data, options);
        return false;
    }
</script>

Areas/Admin/Views/AdminGrafico/VendasSemanal.cshtml
<title>
    @ViewData["Title"] - Gráfico de Vendas
</title>


<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<div id="chart_div" style="width: 900px; height: 500px;"></div>
<script type="text/javascript">
    google.charts.load('current', { 'packages': ['corechart'] });
    google.charts.setOnLoadCallback(carregarDados);

    function carregarDados() {
        $.ajax({
            url: '@Url.Action("VendasLanches", "AdminGrafico")',
            data: { dias: 7 },
            dataType: 'json',
            type: 'GET',
            success: function (xhr, status, error) {
                var err = eval("(" + xhr.responseText + ")");
                toastr.error(err.Message);
            },
            success: function (data) {
                GraficoVendasLanches(data);
                return false;
            }
        });
    }

    function GraficoVendasLanches(data) {
        var dataArray = [['Lanche', 'Quantidade', 'Valores(R$)']];

        $.each(data, function (i, item) {
            dataArray.push([item.lancheNome, item.lanchesQuantidade, item.lanchesValorTotal]);
        });

        var data = google.visualization.arrayToDataTable(dataArray);
        var options = {
            title: 'Lanches - Vendas nos últimos 7 dias',
            chartArea: { width: '70%' },
            colors: ['#b0120a', '#ffab91'],
            hAxis: {
                title: 'Lanches',
                minValue: 0
            },
            vAxis: {
                title: 'Valor total (R$)'
            }
        };
        var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
        chart.draw(data, options);
        return false;
    }
</script>